name = "proxy-img"
main = "src/index.js"
compatibility_date = "2025-10-12"

# Worker configuration
workers_dev = true

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[[kv_namespaces]]
binding = "KV_STATS"
id = "4b4bcfc5cc664fa9b62771f9d3a5d162"
